# Generated by Django 5.2.4 on 2025-07-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'uploaded_document',
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=20, null=True)),
                ('llm_verdict', models.TextField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documentverification.uploadeddocument')),
            ],
            options={
                'db_table': 'extracted_data',
            },
        ),
    ]
