# Generated by Django 5.2.4 on 2025-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentverification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
    ]
