# Generated by Django 5.2.4 on 2025-07-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentverification', '0002_alter_uploadeddocument_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='doc_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
