# Generated by Django 5.2.4 on 2025-07-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentverification', '0003_extracteddata_doc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracteddata',
            name='doc_type',
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Needs Review', 'Needs Review'), ('Unknown', 'Unknown')], default='Pending', max_length=20),
        ),
    ]
