# Generated by Django 5.2.4 on 2025-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentverification', '0004_remove_extracteddata_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
