# Generated by Django 5.2.4 on 2025-07-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentverification', '0005_alter_uploadeddocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file_type',
            field=models.CharField(max_length=150),
        ),
    ]
